name: Infrastructure Automation Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Application Name'
        required: true
        default: 'Ex: my_application_name'
      event_rule_expression:
        description: 'Event Rule Expression'
        required: true
        default: 'Ex: rate(10 minutes)'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          echo "Building and deploying for ${{ github.event.inputs.environment }}"
          echo "Building and deploying for ${{ github.event.inputs.event_rule_expression }}"

      - name: Execute shell script
        run: |
          chmod +x ./scripts/automation_script.sh && ./scripts/automation_script.sh
